

##
## Do not run this every 30 minutes, you'll get a pileup
##

# Generate the list of all videos
cat ~/db.git/yurl_flatfile_db/yurl_queue_2017.txt ~/db.git/yurl_queue_httpcat.txt | sh ~/bin/yurl_filter_videos.sh | grep -v '/playlist' | grep -v '/results' | grep -v '/user' | perl -pe 's{[0-9]+::[0-9]+::}{}g'  | perl -pe 's{[0-9]+::(.*)::[0-9]+}{$1}g' | tee /tmp/yurl_queue_httpcat_videos.txt > /dev/null
cat ~/db.git//yurl_flatfile_db/yurl_queue_2017.txt ~/db.git/yurl_queue_httpcat.txt | grep -i -P '\.mp4' | perl -pe 's{[0-9]+::[0-9]+::}{}g'  | perl -pe 's{[0-9]+::(.*)::[0-9]+}{$1}g' | tee -a /tmp/yurl_queue_httpcat_videos.txt > /dev/null

update_tmp_files() {
	cat ~/db.git/yurl_flatfile_db/videos_download_succeeded.txt   | grep '\.part' | perl -pe 's{::.*}{}g' | sh ~/bin/yurl_filter_videos.sh | uniq | sort | uniq > /tmp/yurl_queue_httpcat_videos_downloaded.txt
	touch /tmp/yurl_queue_httpcat_videos_downloaded.txt ;  comm -23 <(sort /tmp/yurl_queue_httpcat_videos.txt)  <(sort /tmp/yurl_queue_httpcat_videos_downloaded.txt) | grep -v channel | tac | tee /tmp/yurl_queue_httpcat_videos_undownloaded.txt >/dev/null
}

# Find out which videos have not been downloaded
# the list of downloaded videos gets generated by ________
update_tmp_files
#cat ~/db.git/auto/yurl_queue_httpcat_videos.txt | grep -v -f ~/db.git/auto/yurl_queue_httpcat_videos_downloaded.txt | grep -v channel | tac | tee /tmp/yurl_queue_httpcat_videos_undownloaded.txt

# TEMPORARILY REDUCE the number of videos downloaded, the server is getting overloaded.
cat /tmp/yurl_queue_httpcat_videos_undownloaded.txt | sort | uniq | shuf | head -${1:-2} | tee /tmp/yurl_queue_httpcat_videos_undownloaded_reduced.txt

cat /tmp/yurl_queue_httpcat_videos_undownloaded_reduced.txt



# Download them, remove them from the input file, and record which have been downloaded in the output file
# 3rd arg is redundant
touch ~/db.git/auto/yurl_queue_httpcat_videos_failed.txt; chmod 777 ~/bin/youtube_download ; cd ~/github/httpcat && cat /tmp/yurl_queue_httpcat_videos_undownloaded_reduced.txt | groovy download_video_from_list_v2.groovy  /tmp/yurl_queue_httpcat_videos_undownloaded_reduced.txt ~/videos/ /tmp/yurl_queue_httpcat_videos_downloaded.txt ~/db.git/auto/yurl_queue_httpcat_videos_failed.txt 2> /tmp/download_video_from_list.log  | tee -a /tmp/yurl_queue_httpcat_videos_downloaded_unreliable.txt 




#echo "[DEBUG] Finished downloading, updating list of downloaded videos."
# Hmmmmm, /tmp/yurl_queue_httpcat_videos_downloaded.txt is incomplete. Ignore what we generated earlier.

echo "[DEBUG] Updating list of undownloaded videos for next run."
#echo "[DEBUG] Finished"
## Find out which videos have not been downloaded (again - so we have accurate state that we can examine for debugging)
#touch /tmp/yurl_queue_httpcat_videos_downloaded.txt ; cat /tmp/yurl_queue_httpcat_videos.txt | grep -v -f /tmp/yurl_queue_httpcat_videos_downloaded.txt | grep -v channel | tac | tee /tmp/yurl_queue_httpcat_videos_undownloaded.txt >/dev/null

update_tmp_files

echo "[DEBUG] Finished updating list of undownloaded videos for next run."
